[login]

# <必須> メールアドレスとパスワード。
mail = "mail@example.com"
password = "password"

# クッキー保存先のファイル。
# Set-Cookie3 ファイル形式で保存されます。
# 存在しない場合は自動的に作成されます。
# 指定されなかった場合、クッキーは保存されません。
cookieJar = "cookiejar.txt"

[search]
# 一部、コンテンツ検索 API のパラメータをそのまま指定する項目があります。
# 必要に応じてコンテンツ検索 API ドキュメントを参照してください。
# https://site.nicovideo.jp/search-api-docs/search.html

# <必須> 検索キーワード。
q = "ゲーム"

# 検索対象。コンテンツ検索 API のフィールドを指定できます。
# キーワード検索の場合は ["title", "description", "tags"]、
# タグ検索の場合は ["tagsExact"] を指定してください。
# デフォルトではキーワード検索になります。
#targets = ["title", "description", "tags"]

# タイムシフト予約の登録順序。
# コンテンツ検索 API の _sort クエリパラメータと同様に指定してください。
# デフォルトは "+startTime" です。
#sort = "+startTime"

# 生放送の絞り込みに使う JSON ファイル。
# 書式はコンテンツ検索 API の JSON フィルタ指定仕様を参照してください。
jsonFilter = "filters.json"

# 生放送を現在時刻からの相対時間で絞り込みます。
# "1h30m" のような文字列で指定します。この場合は「1時間30分後」を指します。
# 先頭にマイナス記号を置くと過去の時間を指します。
# 利用できる単位は以下の通りです。
#   - "w"   週
#   - "d"   日
#   - "h"   時間
#   - "m"   分
#   - "s"   秒
#   - "ms"  ミリ秒
#   - "us"  マイクロ秒
#openTimeFrom = "30m"       # 生放送の開場時間 範囲開始
#openTimeTo = "1d"          # 生放送の開場時間 範囲終了
startTimeFrom = "30m"       # 生放送の開始時間 範囲開始
#startTimeTo = "1d"         # 生放送の開始時間 範囲終了
#liveEndTimeFrom = "30m"    # 生放送の終了時間 範囲開始
#liveEndTimeTo = "1d"       # 生放送の終了時間 範囲終了

# 生放送を有料生放送かどうかで絞り込みます。
# 有料生放送とは、ネットチケットが必要な放送です。チャンネル登録者無料の
# 生放送や、チャンネル登録者限定の生放送、一部無料（チラ見せ）の生放送を
# 含みます。
# true を指定すると、有料生放送のみタイムシフト予約します。
# false を指定すると、有料ではない生放送のみタイムシフト予約します。
# 指定されなかった場合、有料かどうかによる絞り込みを行いません。
#ppv = false

[warn]

# タイムシフト予約しようとした生放送が、タイムシフトに対応していなかった場合に
# 警告します。
# jsonFilter で timeshiftEnabled が true となっている生放送のみを抽出すれば、
# この問題を防げます。
# デフォルトは true です。
#tsNotSupported = true

# タイムシフト予約しようとした生放送が、既に申し込み期限切れだった場合に
# 警告します。
# 一般会員の場合、[search] セクションで startTimeFrom を "30m" 以上に
# 設定すれば、この問題を防げます。
# デフォルトは true です。
#tsRegistrationExpired = true

# タイムシフトの予約件数上限に達し、タイムシフト予約ができなくなった場合に
# 警告します。
# デフォルトは true です。
#tsMaxReservation = true

[misc]

# タイムシフト予約件数上限に達した場合に、視聴期限が切れた古い
# タイムシフト予約を上書きします。
# デフォルトは false です。
#overwrite = false

# タイムアウト時間の設定。単位は秒です。
# サーバーのレスポンスが受信できなくなってから指定秒数だけ経過すると
# 処理を中断します。
# 指定されなかった場合、タイムアウトは発生しなくなります。
timeout = 300

# HTTP リクエストの User-Agent ヘッダ。
# 指定されなかった場合、User-Agent ヘッダは送信されません。
userAgent = "ts-machine (private app)"

# コンテンツ検索APIの _context クエリパラメータ。
# 指定されなかった場合、_context クエリパラメータは送信されません。
context = "ts-machine (private app)"
